import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import { ThemeProvider } from "@/context/ThemeContext";

import AuthProvider from "@/components/AuthProvider/AuthProvider";
export const metadata = {
  title: "The Future Code",
  description: "Generated by Azhar Ali Sheeno",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`} suppressHydrationWarning={true}>

        <ThemeProvider >
        
          <AuthProvider>

        <div className="md:max-w-[1366px] min-h-screen mx-auto md:px-[60px] flex flex-col justify-between">
        <Navbar/>
        {children}
        <Footer/>
        </div>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
